spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/jwt_security
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8090